import 'package:flutter/material.dart';
import '../high_q_paginated_drop_down.dart';

class HighQDropDown<T> extends StatelessWidget {
  final Widget _delegate;

  HighQDropDown({
    Key? key,
    List<MenuItemModel<T>>? items,
    HighQPaginatedDropdownController<T>? controller,
    T? initialValue,
    bool enabled = true,
    void Function(T? value)? onChanged,
    VoidCallback? onDisabledTap,
    SearchProps searchProps = const SearchProps(),
    IconProps iconProps = const IconProps(),
    StyleProps styleProps = const StyleProps(),
    BuilderProps<T> builderProps = const BuilderProps(),
  }) : _delegate = HighQSingleDropDown<T>(
         key: key,
         items: items,
         controller: controller,
         initialValue: initialValue,
         enabled: enabled,
         onChanged: onChanged,
         onDisabledTap: onDisabledTap,
         searchProps: searchProps,
         iconProps: iconProps,
         styleProps: styleProps,
         builderProps: builderProps,
       ),
       super(key: null);

  HighQDropDown.paginated({
    Key? key,
    required PaginatedRequestProps<T> requestProps,
    HighQPaginatedDropdownController<T>? controller,
    void Function(T? value)? onChanged,
    bool enabled = true,
    MenuItemModel<T>? initialFutureValue,
    VoidCallback? onDisabledTap,
    SearchProps searchProps = const SearchProps(),
    IconProps iconProps = const IconProps(),
    StyleProps styleProps = const StyleProps(),
    BuilderProps<T> builderProps = const BuilderProps(),
  }) : _delegate = HighQPaginatedDropdown<T>(
         key: key,
         requestProps: requestProps,
         controller: controller,
         onChanged: onChanged,
         enabled: enabled,
         initialFutureValue: initialFutureValue,
         onDisabledTap: onDisabledTap,
         searchProps: searchProps,
         iconProps: iconProps,
         styleProps: styleProps,
         builderProps: builderProps,
       ),
       super(key: null);

  HighQDropDown.multiSelect({
    Key? key,
    ItemsLogicProps<T> itemsLogicProps = const ItemsLogicProps(),
    FilterAndCompareProps<T> filterAndCompareProps = const FilterAndCompareProps(),
    DropDownDecoratorProps dropdownDecorator = const DropDownDecoratorProps(),
    SelectedItemDecorationPros selectedItemDecorationPros = const SelectedItemDecorationPros(),
    ConfirmButtonProps confirmButtonProps = const ConfirmButtonProps(),
    CancelButtonProps? cancelButtonProps,
    ClearButtonProps clearButtonProps = const ClearButtonProps(),
    Widget? loadingWidget,
    DropdownButtonProps dropdownButtonProps = const DropdownButtonProps(),
    ValidatorProps<T> validatorProps = const ValidatorProps(),
    PopupPropsMultiSelection<T> popupProps = const PopupPropsMultiSelection.menu(),
    MethodLogicProps<T> methodLogicProps = const MethodLogicProps(),
    String moreText = 'Show more',
    bool makeButtonsInRow = false,
    String lessText = 'Show less',
    MultiSelectController<T>? controller,
    int maxDisplayCount = 3,
    bool enabled = true,
    SearchProps searchProps = const SearchProps(),
    StyleProps styleProps = const StyleProps(),
  }) : _delegate = HighQMultiSelectDropDown<T>(
         key: key,
         itemsLogicProps: itemsLogicProps,
         filterAndCompareProps: filterAndCompareProps,
         dropdownDecorator: dropdownDecorator,
         selectedItemDecorationPros: selectedItemDecorationPros,
         confirmButtonProps: confirmButtonProps,
         cancelButtonProps: cancelButtonProps,
         clearButtonProps: clearButtonProps,
         loadingWidget: loadingWidget,
         dropdownButtonProps: dropdownButtonProps,
         validatorProps: validatorProps,
         popupProps: popupProps,
         methodLogicProps: methodLogicProps,
         moreText: moreText,
         makeButtonsInRow: makeButtonsInRow,
         lessText: lessText,
         controller: controller,
         maxDisplayCount: maxDisplayCount,
         enabled: enabled,
         searchProps: searchProps,
         styleProps: styleProps,
       ),
       super(key: null);

  HighQDropDown.paginatedMultiSelect({
    Key? key,
    Future<List<T>> Function(int page, String? filter)? paginatedRequest,
    int requestItemCount = 15,
    ItemsLogicProps<T> itemsLogicProps = const ItemsLogicProps(),
    FilterAndCompareProps<T> filterAndCompareProps = const FilterAndCompareProps(),
    DropDownDecoratorProps dropdownDecorator = const DropDownDecoratorProps(),
    SelectedItemDecorationPros selectedItemDecorationPros = const SelectedItemDecorationPros(),
    ConfirmButtonProps confirmButtonProps = const ConfirmButtonProps(),
    CancelButtonProps? cancelButtonProps,
    ClearButtonProps clearButtonProps = const ClearButtonProps(),
    Widget? loadingWidget,
    DropdownButtonProps dropdownButtonProps = const DropdownButtonProps(),
    ValidatorProps<T> validatorProps = const ValidatorProps(),
    PopupPropsMultiSelection<T> popupProps = const PopupPropsMultiSelection.menu(),
    MethodLogicProps<T> methodLogicProps = const MethodLogicProps(),
    String moreText = 'Show more',
    bool makeButtonsInRow = false,
    String lessText = 'Show less',
    MultiSelectController<T>? controller,
    int maxDisplayCount = 3,
    bool enabled = true,
    SearchProps searchProps = const SearchProps(),
    StyleProps styleProps = const StyleProps(),
  }) : _delegate = HighQMultiSelectPaginatedDropDown<T>(
         key: key,
         paginatedRequest: paginatedRequest,
         requestItemCount: requestItemCount,
         itemsLogicProps: itemsLogicProps,
         filterAndCompareProps: filterAndCompareProps,
         dropdownDecorator: dropdownDecorator,
         selectedItemDecorationPros: selectedItemDecorationPros,
         confirmButtonProps: confirmButtonProps,
         cancelButtonProps: cancelButtonProps,
         clearButtonProps: clearButtonProps,
         loadingWidget: loadingWidget,
         dropdownButtonProps: dropdownButtonProps,
         validatorProps: validatorProps,
         popupProps: popupProps,
         methodLogicProps: methodLogicProps,
         moreText: moreText,
         makeButtonsInRow: makeButtonsInRow,
         lessText: lessText,
         controller: controller,
         maxDisplayCount: maxDisplayCount,
         enabled: enabled,
         searchProps: searchProps,
         styleProps: styleProps,
       ),
       super(key: null);

  @override
  Widget build(BuildContext context) {
    return _delegate;
  }
}
